data_path: /data/home/yujinglou/project/dataset/cpnet_dataset/

task: correspondence
task_type: embedding
dist_type: 'geodesic'

gpu: 0
embedding_size: 128
batch_size: 4
num_workers: 1
max_epoch: 400
lr: 0.001
weight_decay: 0.001
lr_step: 10
lr_decay: 0.9
eval_step: 1
margin: 1
dist_thr: -1
laplacian_reg: false
class_name: airplane
test_vis: true

defaults:
  - network: pointnet2

hydra:
  run:
    dir: log/${class_name}/${network.name}
  sweep:
    dir: log
    subdir: ${class_name}/${network.name}